# Generated by Django 5.2.17 on 2026-09-19 13:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. cad_parser, telemetry_analyzer', max_length=100, unique=True)),
                ('description', models.TextField()),
                ('permission_required', models.CharField(choices=[('Admin', 'Admin'), ('Engineer', 'Engineer'), ('Analyst', 'Analyst'), ('Operator', 'Operator')], default='Engineer', help_text='Minimum role required to authorize this tool for agent execution', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Industrial Tool',
                'verbose_name_plural': 'Industrial Tools',
                'ordering': ['name'],
            },
        ),
    ]
