# Generated by Django 5.2.17 on 2026-09-19 13:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. llama-3.3-70b-instruct, qwen-2.5-vl', max_length=255, unique=True)),
                ('provider', models.CharField(choices=[('OLLAMA', 'Local Ollama'), ('VLLM', 'Local vLLM Server'), ('LLAMACPP', 'Local llama.cpp'), ('HUGGINGFACE_LOCAL', 'HuggingFace Local Pipeline'), ('MOCK', 'Deterministic Mock Adapter (Zero GPU)')], default='MOCK', max_length=50)),
                ('model_type', models.CharField(choices=[('LLM', 'Large Language Model'), ('VISION', 'Vision Multimodal LLM'), ('EMBEDDING', 'Embedding Model'), ('VECTOR_DB', 'Vector Database Engine')], default='LLM', max_length=50)),
                ('endpoint', models.CharField(blank=True, help_text='Local endpoint e.g. http://127.0.0.1:11434', max_length=255)),
                ('status', models.CharField(choices=[('ONLINE', 'Online & Ready'), ('OFFLINE', 'Offline'), ('STANDBY', 'Standby / Loading')], default='ONLINE', max_length=20)),
                ('capabilities', models.JSONField(blank=True, default=dict, help_text='Context window, quant level, modalities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Model Registry Entry',
                'verbose_name_plural': 'Model Registry',
                'ordering': ['model_type', 'name'],
            },
        ),
    ]
