# Generated by Django 5.2.17 on 2026-09-19 13:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SovereigntyReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('models_used', models.JSONField(default=list, help_text='List of local models utilized')),
                ('files_accessed', models.JSONField(default=list, help_text='Vault files read during execution')),
                ('tools_used', models.JSONField(default=list, help_text='Tool IDs/names invoked')),
                ('external_requests', models.IntegerField(default=0, help_text='Count of outbound external network requests made (Must be 0 in sovereign operation)')),
                ('network_status', models.CharField(default='AIR_GAPPED_LOCAL', help_text='Network confinement state at time of run', max_length=50)),
                ('integrity_hash', models.CharField(help_text='SHA-256 tamper-evident hash of all receipt parameters', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sovereignty_receipts', to='agents.agenttask')),
            ],
            options={
                'verbose_name': 'Sovereignty Receipt',
                'verbose_name_plural': 'Sovereignty Receipts',
                'ordering': ['-created_at'],
            },
        ),
    ]
