# Generated by Django 5.2.17 on 2026-09-19 14:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='chunk_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of chunks indexed.'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='rag_indexed',
            field=models.BooleanField(default=False, help_text='True once this KB has been embedded and indexed into the vector store.'),
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_document_name', models.CharField(blank=True, max_length=512)),
                ('chunk_index', models.PositiveIntegerField(default=0, help_text='Zero-based index of this chunk within the source document.')),
                ('content', models.TextField(help_text='Raw text content of this chunk.')),
                ('embedding', models.JSONField(blank=True, default=list, help_text='Local embedding vector (float list).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgebase')),
            ],
            options={
                'verbose_name': 'Knowledge Chunk',
                'verbose_name_plural': 'Knowledge Chunks',
                'ordering': ['knowledge_base', 'chunk_index'],
            },
        ),
    ]
