# Generated by Django 5.2.17 on 2026-09-19 13:29

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('size', models.BigIntegerField(default=0, help_text='Size in bytes')),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('SCANNING', 'Scanning / Ingesting'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='READY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Confidential Document',
                'verbose_name_plural': 'Confidential Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
